# Generated by Django 3.0.8 on 2020-07-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatoapp', '0002_auto_20200210_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='subject',
            field=models.CharField(blank=True, choices=[('Business', 'Business'), ('CoursePythonI', 'Course: Python I'), ('CoursePythonOOP', 'Course: Python OOP'), ('AnalistaLinux', 'Course: Analista Linux'), ('CourseFlask', 'Course: Python Flask'), ('Q&A', 'Q&A'), ('R&S', 'R&S')], db_column='subject', db_index=True, default=6, max_length=20, null=True, verbose_name='subject'),
        ),
    ]
